name: heart-failure-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.2.5
  - pandas=2.2.3
  - matplotlib=3.10.1
  - matplotlib-inline=0.1.7
  - scikit-learn=1.6.1
  - ipykernel
